function escapeMd(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

export function moduleToMarkdown(module, notes, progress) {
  const lines = []
  lines.push(`# ${module.subject}`)
  lines.push('')
  lines.push(`> Generated by Learning Agent at ${new Date().toLocaleString()}`)
  lines.push('')

  const lessonTopics = module.mainTopics.filter((t) => t.title !== 'Roadmap')
  const allItems = lessonTopics.flatMap((t) => t.subtopics.flatMap((s) => s.items))
  if (allItems.length && progress) {
    const done = allItems.filter((i) => lessonTopics.some((t) => t.subtopics.some((s) => progress[itemKey(t.title, s.title, i)] === 'done'))).length
    lines.push(`**Progress:** ${done}/${allItems.length} lessons done`)
    lines.push('')
  }

  module.mainTopics.forEach((main, mi) => {
    lines.push(`## ${mi + 1}. ${main.title}`)
    lines.push('')
    main.subtopics.forEach((sub, si) => {
      lines.push(`### ${mi + 1}.${si + 1} ${sub.title}`)
      lines.push('')
      sub.items.forEach((item, ii) => {
        const key = itemKey(main.title, sub.title, item)
        const mark = progress?.[key] === 'done' ? '[x]' : progress?.[key] === 'in-progress' ? '[/]' : '[ ]'
        lines.push(`- ${mark} **${mi + 1}.${si + 1}.${ii + 1}. ${item}**`)
        const note = notes[key]
        if (note) {
          lines.push('')
          lines.push(note.summary || '')
          if (note.keyPoints?.length) {
            lines.push('')
            lines.push('Key points:')
            note.keyPoints.forEach((kp) => lines.push(`- ${kp}`))
          }
          if (note.learnByDoing) {
            lines.push('')
            lines.push(`*Practice:* ${note.learnByDoing}`)
          }
          if (note.resources?.length) {
            lines.push('')
            lines.push('Resources:')
            note.resources.forEach((r) => lines.push(`- ${r}`))
          }
        } else {
          lines.push('')
        }
      })
    })
    lines.push('')
  })

  return lines.join('\n')
}

export function itemKey(mainTitle, subTitle, item) {
  return `${mainTitle}::${subTitle}::${item}`
}

function csvCell(text) {
  const s = String(text ?? '')
  const escaped = s.replace(/"/g, '""')
  return `"${escaped}"`
}

function htmlEscape(text) {
  return String(text ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br>')
}

/* Anki CSV export. Columns: Front, Back, Tags (Anki's plain-text CSV import).
   Front = lesson title, Back = note summary + key points + practice. */
export function moduleToAnkiCsv(module, notes) {
  const rows = ['Front,Back,Tags']
  if (!module?.mainTopics) return rows.join('\n')
  const lessonTopics = module.mainTopics.filter((t) => t.title !== 'Roadmap')
  for (const main of lessonTopics) {
    for (const sub of main.subtopics || []) {
      for (const item of sub.items || []) {
        const key = itemKey(main.title, sub.title, item)
        const note = notes[key]
        const backParts = []
        if (note?.summary) backParts.push(`<p>${htmlEscape(note.summary)}</p>`)
        if (note?.keyPoints?.length) {
          backParts.push('<ul>' + note.keyPoints.map((k) => `<li>${htmlEscape(k)}</li>`).join('') + '</ul>')
        }
        if (note?.learnByDoing) backParts.push(`<p><b>Practice:</b> ${htmlEscape(note.learnByDoing)}</p>`)
        if (note?.resources?.length) {
          backParts.push('<ul>' + note.resources.map((r) => `<li>${htmlEscape(r)}</li>`).join('') + '</ul>')
        }
        const back = backParts.length ? backParts.join('') : ''
        const tag = `${module.subject || 'langlea'}`.replace(/[^a-zA-Z0-9_:-]/g, '_')
        rows.push(`${csvCell(`${main.title} › ${sub.title} › ${item}`)},${csvCell(back)},${csvCell(tag)}`)
      }
    }
  }
  return rows.join('\n')
}
