function escapeMd(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

export function moduleToMarkdown(module, notes) {
  const lines = []
  lines.push(`# ${module.subject}`)
  lines.push('')
  lines.push(`> Generated by Learning Agent at ${new Date().toLocaleString()}`)
  lines.push('')

  module.mainTopics.forEach((main, mi) => {
    lines.push(`## ${mi + 1}. ${main.title}`)
    lines.push('')
    main.subtopics.forEach((sub, si) => {
      lines.push(`### ${mi + 1}.${si + 1} ${sub.title}`)
      lines.push('')
      sub.items.forEach((item, ii) => {
        lines.push(`**${mi + 1}.${si + 1}.${ii + 1}. ${item}**`)
        const note = notes[itemKey(main.title, sub.title, item)]
        if (note) {
          lines.push('')
          lines.push(note.summary || '')
          if (note.keyPoints?.length) {
            lines.push('')
            lines.push('Key points:')
            note.keyPoints.forEach((kp) => lines.push(`- ${kp}`))
          }
          if (note.learnByDoing) {
            lines.push('')
            lines.push(`*Practice:* ${note.learnByDoing}`)
          }
          if (note.resources?.length) {
            lines.push('')
            lines.push('Resources:')
            note.resources.forEach((r) => lines.push(`- ${r}`))
          }
        } else {
          lines.push('')
        }
      })
    })
    lines.push('')
  })

  return lines.join('\n')
}

export function itemKey(mainTitle, subTitle, item) {
  return `${mainTitle}::${subTitle}::${item}`
}
