function escapeMd(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

export function moduleToMarkdown(module, notes, progress) {
  const lines = []
  lines.push(`# ${module.subject}`)
  lines.push('')
  lines.push(`> Generated by Learning Agent at ${new Date().toLocaleString()}`)
  lines.push('')

  const lessonTopics = module.mainTopics.filter((t) => t.title !== 'Roadmap')
  const allItems = lessonTopics.flatMap((t) => t.subtopics.flatMap((s) => s.items))
  if (allItems.length && progress) {
    const done = allItems.filter((i) => lessonTopics.some((t) => t.subtopics.some((s) => progress[itemKey(t.title, s.title, i)] === 'done'))).length
    lines.push(`**Progress:** ${done}/${allItems.length} lessons done`)
    lines.push('')
  }

  module.mainTopics.forEach((main, mi) => {
    lines.push(`## ${mi + 1}. ${main.title}`)
    lines.push('')
    main.subtopics.forEach((sub, si) => {
      lines.push(`### ${mi + 1}.${si + 1} ${sub.title}`)
      lines.push('')
      sub.items.forEach((item, ii) => {
        const key = itemKey(main.title, sub.title, item)
        const mark = progress?.[key] === 'done' ? '[x]' : progress?.[key] === 'in-progress' ? '[/]' : '[ ]'
        lines.push(`- ${mark} **${mi + 1}.${si + 1}.${ii + 1}. ${item}**`)
        const note = notes[key]
        if (note) {
          lines.push('')
          lines.push(note.summary || '')
          if (note.keyPoints?.length) {
            lines.push('')
            lines.push('Key points:')
            note.keyPoints.forEach((kp) => lines.push(`- ${kp}`))
          }
          if (note.learnByDoing) {
            lines.push('')
            lines.push(`*Practice:* ${note.learnByDoing}`)
          }
          if (note.resources?.length) {
            lines.push('')
            lines.push('Resources:')
            note.resources.forEach((r) => lines.push(`- ${r}`))
          }
        } else {
          lines.push('')
        }
      })
    })
    lines.push('')
  })

  return lines.join('\n')
}

export function itemKey(mainTitle, subTitle, item) {
  return `${mainTitle}::${subTitle}::${item}`
}
