import { test, expect } from '@playwright/test'

const MOCK_PROFILE = {
  id: 'mock-e2e',
  name: 'Mock AI',
  baseUrl: 'http://localhost:5001/v1',
  apiKey: '',
  models: ['mock-gpt']
}

const SELECTION = {
  profileId: 'mock-e2e',
  model: 'mock-gpt',
  chatProfileId: 'mock-e2e',
  chatModel: 'mock-gpt',
  reviewProfileId: 'mock-e2e',
  reviewModel: 'mock-gpt'
}

async function seedMockProfile(page) {
  await page.addInitScript(([profile, selection]) => {
    localStorage.setItem('la-ai-profiles', JSON.stringify([profile]))
    localStorage.setItem('la-ai-selection', JSON.stringify(selection))
  }, [MOCK_PROFILE, SELECTION])
}

test.describe('Learning Agent', () => {
  test.beforeEach(async ({ page }) => {
    await seedMockProfile(page)
  })

  test('generates a full module from the mock AI and opens it', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: /New Topic/i }).click()

    await page.getByPlaceholder(/Machine learning, Guitar/i).fill('TypeScript')
    await page.getByRole('button', { name: /Research & Generate Module/i }).click()

    // generation phase → module phase
    await expect(page.getByText('Researching your module…')).toBeVisible({ timeout: 30000 })
    await expect(page.locator('.workspace')).toBeVisible({ timeout: 60000 })
    await expect(page.getByText(/LangLea · TypeScript/)).toBeVisible({ timeout: 30000 })

    // mock subtopics should be present in the topic tree
    await expect(page.getByRole('button', { name: /Core methods/i }).first()).toBeVisible()
    await expect(page.getByText(/Math basics/i).first()).toBeVisible()
  })

  test('generates a study note and tracks progress', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: /New Topic/i }).click()
    await page.getByPlaceholder(/Machine learning, Guitar/i).fill('TypeScript')
    await page.getByRole('button', { name: /Research & Generate Module/i }).click()

    await expect(page.locator('.workspace')).toBeVisible({ timeout: 60000 })
    await expect(page.getByText(/LangLea · TypeScript/)).toBeVisible({ timeout: 30000 })

    // open a lesson item
    await page.getByRole('button', { name: /Core methods/i }).first().click()
    await page.getByRole('button', { name: /Main algorithm/i }).first().click()

    // note is generated by mock AI
    await expect(page.getByText('A concise explanation.')).toBeVisible({ timeout: 30000 })

    // cycle status to done via the status button
    const statusBtn = page.locator('.status-btn').first()
    await statusBtn.click() // todo → in-progress
    await statusBtn.click() // in-progress → done
    await expect(page.getByText(/1\/30 completed/i)).toBeVisible({ timeout: 10000 })
  })

  test('saves and reloads a module from the dashboard', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: /New Topic/i }).click()
    await page.getByPlaceholder(/Machine learning, Guitar/i).fill('TypeScript')
    await page.getByRole('button', { name: /Research & Generate Module/i }).click()

    await expect(page.locator('.workspace')).toBeVisible({ timeout: 60000 })
    await expect(page.getByText(/LangLea · TypeScript/)).toBeVisible({ timeout: 30000 })

    // wait for the autosave debounce, then go back to dashboard
    await page.waitForTimeout(1200)
    await page.getByRole('button', { name: /Modules/i }).click()

    // module appears in the dashboard grid
    await expect(page.getByText('TypeScript').first()).toBeVisible({ timeout: 10000 })
    await expect(page.getByRole('button', { name: /Open Course/i }).first()).toBeVisible()

    // reopen it
    await page.getByRole('button', { name: /Open Course/i }).first().click()
    await expect(page.locator('.workspace')).toBeVisible()
  })

  test('manual mode accepts user-provided topics without AI', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: /New Topic/i }).click()

    await page.getByPlaceholder(/Machine learning, Guitar/i).fill('My custom module')
    await page.getByRole('button', { name: /Manual — I provide outline/i }).click()

    await page.getByPlaceholder(/HTML and CSS/i).fill('# Topic One\n## Subtopic A\n- Lesson A\n# Topic Two')
    await page.getByRole('button', { name: /Research & Generate Module/i }).click()

    await expect(page.locator('.workspace')).toBeVisible({ timeout: 30000 })
    await expect(page.getByRole('button', { name: /Topic One/i })).toBeVisible()
    await expect(page.getByRole('button', { name: /Topic Two/i })).toBeVisible()
  })

  test('command palette opens with Ctrl+K and jumps to a lesson', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: /New Topic/i }).click()
    await page.getByPlaceholder(/Machine learning, Guitar/i).fill('TypeScript')
    await page.getByRole('button', { name: /Research & Generate Module/i }).click()

    await expect(page.locator('.workspace')).toBeVisible({ timeout: 60000 })
    await expect(page.getByText(/LangLea · TypeScript/)).toBeVisible({ timeout: 30000 })

    await page.keyboard.press('Control+K')
    await expect(page.getByPlaceholder(/Type a lesson, action/i)).toBeVisible()

    await page.keyboard.type('Main algorithm')
    await page.keyboard.press('Enter')

    // selection opens the content panel
    await expect(page.getByText('A concise explanation.')).toBeVisible({ timeout: 30000 })
  })
})
